# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIadaptive_feedback.ui'
#
# Created: Wed Sep 13 17:08:23 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1152, 781)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        #Form.setStyleSheet(_fromUtf8("background-color: white"))
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 205))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 1, 0, 1, 1)
        self.sb_array_len = QtGui.QSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sb_array_len.setFont(font)
        self.sb_array_len.setMaximum(5000)
        self.sb_array_len.setSingleStep(10)
        self.sb_array_len.setProperty("value", 100)
        self.sb_array_len.setObjectName(_fromUtf8("sb_array_len"))
        self.gridLayout_5.addWidget(self.sb_array_len, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.sb_time_delay = QtGui.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sb_time_delay.setFont(font)
        self.sb_time_delay.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_time_delay.setMaximum(10.0)
        self.sb_time_delay.setSingleStep(0.01)
        self.sb_time_delay.setProperty("value", 0.1)
        self.sb_time_delay.setObjectName(_fromUtf8("sb_time_delay"))
        self.gridLayout_5.addWidget(self.sb_time_delay, 1, 1, 1, 1)
        self.sb_averaging = QtGui.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sb_averaging.setFont(font)
        self.sb_averaging.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_averaging.setMaximum(100.0)
        self.sb_averaging.setSingleStep(10.0)
        self.sb_averaging.setProperty("value", 10.0)
        self.sb_averaging.setObjectName(_fromUtf8("sb_averaging"))
        self.gridLayout_5.addWidget(self.sb_averaging, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.sb_go_recalc_delay = QtGui.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sb_go_recalc_delay.setFont(font)
        self.sb_go_recalc_delay.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_go_recalc_delay.setMinimum(1.0)
        self.sb_go_recalc_delay.setMaximum(100.0)
        self.sb_go_recalc_delay.setSingleStep(1.0)
        self.sb_go_recalc_delay.setProperty("value", 1.0)
        self.sb_go_recalc_delay.setObjectName(_fromUtf8("sb_go_recalc_delay"))
        self.gridLayout_5.addWidget(self.sb_go_recalc_delay, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 3, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 4, 4, 1, 2)
        self.pb_start_feedback = QtGui.QPushButton(Form)
        self.pb_start_feedback.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pb_start_feedback.setFont(font)
        self.pb_start_feedback.setStyleSheet(_fromUtf8("color: rgb(85, 255, 127);"))
        self.pb_start_feedback.setObjectName(_fromUtf8("pb_start_feedback"))
        self.gridLayout.addWidget(self.pb_start_feedback, 13, 2, 1, 1)
        self.label_8 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 13, 0, 1, 1)
        self.pb_start_statistics = QtGui.QPushButton(Form)
        self.pb_start_statistics.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pb_start_statistics.setFont(font)
        self.pb_start_statistics.setStyleSheet(_fromUtf8("color: rgb(85, 255, 127);"))
        self.pb_start_statistics.setObjectName(_fromUtf8("pb_start_statistics"))
        self.gridLayout.addWidget(self.pb_start_statistics, 13, 4, 1, 2)
        self.sb_feedback_rep = QtGui.QDoubleSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sb_feedback_rep.setFont(font)
        self.sb_feedback_rep.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_feedback_rep.setMinimum(1.0)
        self.sb_feedback_rep.setMaximum(100.0)
        self.sb_feedback_rep.setSingleStep(1.0)
        self.sb_feedback_rep.setProperty("value", 3.0)
        self.sb_feedback_rep.setObjectName(_fromUtf8("sb_feedback_rep"))
        self.gridLayout.addWidget(self.sb_feedback_rep, 13, 1, 1, 1)
        self.widget_2 = QtGui.QWidget(Form)
        self.widget_2.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout.addWidget(self.widget_2, 0, 4, 1, 2)
        self.groupBox = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 205))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.le_b = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_b.setFont(font)
        self.le_b.setObjectName(_fromUtf8("le_b"))
        self.gridLayout_3.addWidget(self.le_b, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.le_c = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_c.setFont(font)
        self.le_c.setObjectName(_fromUtf8("le_c"))
        self.gridLayout_3.addWidget(self.le_c, 2, 1, 1, 1)
        self.le_a = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_a.setFont(font)
        self.le_a.setObjectName(_fromUtf8("le_a"))
        self.gridLayout_3.addWidget(self.le_a, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.le_of = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_of.setFont(font)
        self.le_of.setObjectName(_fromUtf8("le_of"))
        self.gridLayout_3.addWidget(self.le_of, 3, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 4, 0, 1, 3)
        self.widget = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(600, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 3)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_8.addWidget(self.label_10, 1, 0, 1, 1)
        self.sb_afeed_fraction = QtGui.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sb_afeed_fraction.setFont(font)
        self.sb_afeed_fraction.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_afeed_fraction.setMaximum(1.0)
        self.sb_afeed_fraction.setSingleStep(0.1)
        self.sb_afeed_fraction.setProperty("value", 0.7)
        self.sb_afeed_fraction.setObjectName(_fromUtf8("sb_afeed_fraction"))
        self.gridLayout_8.addWidget(self.sb_afeed_fraction, 1, 1, 1, 1)
        self.sb_ref_orbit_nread = QtGui.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sb_ref_orbit_nread.setFont(font)
        self.sb_ref_orbit_nread.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_ref_orbit_nread.setDecimals(0)
        self.sb_ref_orbit_nread.setMinimum(1.0)
        self.sb_ref_orbit_nread.setMaximum(100.0)
        self.sb_ref_orbit_nread.setSingleStep(1.0)
        self.sb_ref_orbit_nread.setProperty("value", 1.0)
        self.sb_ref_orbit_nread.setObjectName(_fromUtf8("sb_ref_orbit_nread"))
        self.gridLayout_8.addWidget(self.sb_ref_orbit_nread, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 7, 0, 1, 3)
        self.groupBox_5 = QtGui.QGroupBox(Form)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.pb_load_settings = QtGui.QPushButton(self.groupBox_5)
        self.pb_load_settings.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_load_settings.setFont(font)
        self.pb_load_settings.setStyleSheet(_fromUtf8("color: rgb(51, 255, 255);"))
        self.pb_load_settings.setObjectName(_fromUtf8("pb_load_settings"))
        self.gridLayout_10.addWidget(self.pb_load_settings, 1, 1, 1, 1)
        self.pb_save_settings = QtGui.QPushButton(self.groupBox_5)
        self.pb_save_settings.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_save_settings.setFont(font)
        self.pb_save_settings.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.pb_save_settings.setObjectName(_fromUtf8("pb_save_settings"))
        self.gridLayout_10.addWidget(self.pb_save_settings, 1, 2, 1, 1)
        self.cb_load_settings = QtGui.QComboBox(self.groupBox_5)
        self.cb_load_settings.setObjectName(_fromUtf8("cb_load_settings"))
        self.gridLayout_10.addWidget(self.cb_load_settings, 0, 1, 1, 2)
        self.gridLayout.addWidget(self.groupBox_5, 7, 5, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.le_warn = QtGui.QLineEdit(self.groupBox_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.le_warn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_warn.setFont(font)
        self.le_warn.setObjectName(_fromUtf8("le_warn"))
        self.gridLayout_9.addWidget(self.le_warn, 1, 1, 1, 1)
        self.cb_update_display = QtGui.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_update_display.setFont(font)
        self.cb_update_display.setChecked(True)
        self.cb_update_display.setObjectName(_fromUtf8("cb_update_display"))
        self.gridLayout_9.addWidget(self.cb_update_display, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 7, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Ocelot Interface", None))
        self.groupBox_2.setTitle(_translate("Form", "Statistics Data Control", None))
        self.label_3.setText(_translate("Form", "Reading Delay (s)", None))
        self.label_2.setText(_translate("Form", "Array Length", None))
        self.label_7.setText(_translate("Form", "Averaging Over (%)", None))
        self.label_9.setText(_translate("Form", "Recalculate GO (s)", None))
        self.pb_start_feedback.setText(_translate("Form", "Start Feedback", None))
        self.label_8.setText(_translate("Form", "Apply Feedback Every s  ", None))
        self.pb_start_statistics.setText(_translate("Form", "Statistics Accum On", None))
        self.groupBox.setTitle(_translate("Form", "Objective Function", None))
        self.label_6.setText(_translate("Form", "Objective Function   ", None))
        self.label.setText(_translate("Form", "A:", None))
        self.label_4.setText(_translate("Form", "B:", None))
        self.label_5.setText(_translate("Form", "C:", None))
        self.groupBox_3.setTitle(_translate("Form", "Correction control", None))
        self.label_10.setText(_translate("Form", "Apply Fraction", None))
        self.label_11.setText(_translate("Form", "Ref Orbit avaraging over last (readings)", None))
        self.groupBox_5.setTitle(_translate("Form", "Load Settings", None))
        self.pb_load_settings.setText(_translate("Form", "Load", None))
        self.pb_save_settings.setText(_translate("Form", "Save", None))
        self.groupBox_4.setTitle(_translate("Form", "Indication", None))
        self.cb_update_display.setText(_translate("Form", "Update Main Display", None))

