# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uicorrelation.ui'
#
# Created: Mon Sep 04 21:47:36 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1222, 892)
        MainWindow.setMinimumSize(QtCore.QSize(1150, 0))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_30 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 128))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_24 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.gridLayout_25 = QtGui.QGridLayout()
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.pb_statistics_start = QtGui.QPushButton(self.groupBox_4)
        self.pb_statistics_start.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pb_statistics_start.setFont(font)
        self.pb_statistics_start.setStyleSheet(_fromUtf8("color: rgb(85, 255, 127);"))
        self.pb_statistics_start.setObjectName(_fromUtf8("pb_statistics_start"))
        self.horizontalLayout_24.addWidget(self.pb_statistics_start)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        self.gridLayout_25.addLayout(self.verticalLayout_12, 2, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_30.addWidget(self.label_12)
        self.sb_n_shots = QtGui.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_n_shots.setFont(font)
        self.sb_n_shots.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_n_shots.setDecimals(0)
        self.sb_n_shots.setMinimum(10.0)
        self.sb_n_shots.setMaximum(10000.0)
        self.sb_n_shots.setSingleStep(100.0)
        self.sb_n_shots.setProperty("value", 1000.0)
        self.sb_n_shots.setObjectName(_fromUtf8("sb_n_shots"))
        self.horizontalLayout_30.addWidget(self.sb_n_shots)
        self.verticalLayout_3.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_23.addWidget(self.label_7)
        self.sb_update_rate = QtGui.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_update_rate.setFont(font)
        self.sb_update_rate.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_update_rate.setMinimum(0.1)
        self.sb_update_rate.setMaximum(10.0)
        self.sb_update_rate.setSingleStep(0.1)
        self.sb_update_rate.setProperty("value", 1.0)
        self.sb_update_rate.setObjectName(_fromUtf8("sb_update_rate"))
        self.horizontalLayout_23.addWidget(self.sb_update_rate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.gridLayout_25.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_25, 4, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cb_disp = QtGui.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_disp.setFont(font)
        self.cb_disp.setObjectName(_fromUtf8("cb_disp"))
        self.horizontalLayout.addWidget(self.cb_disp)
        self.cb_sase = QtGui.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_sase.setFont(font)
        self.cb_sase.setObjectName(_fromUtf8("cb_sase"))
        self.horizontalLayout.addWidget(self.cb_sase)
        self.gridLayout_24.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_4, 2, 0, 1, 2)
        self.w_orbit = QtGui.QWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_orbit.sizePolicy().hasHeightForWidth())
        self.w_orbit.setSizePolicy(sizePolicy)
        self.w_orbit.setMinimumSize(QtCore.QSize(650, 400))
        self.w_orbit.setStyleSheet(_fromUtf8(""))
        self.w_orbit.setObjectName(_fromUtf8("w_orbit"))
        self.gridLayout_30.addWidget(self.w_orbit, 0, 0, 1, 2)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.tabWidget_2)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1222, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.action_Parameters = QtGui.QAction(MainWindow)
        self.action_Parameters.setObjectName(_fromUtf8("action_Parameters"))
        self.actionLoad_Golden_Orbit = QtGui.QAction(MainWindow)
        self.actionLoad_Golden_Orbit.setObjectName(_fromUtf8("actionLoad_Golden_Orbit"))
        self.actionSave_Golden_Orbit = QtGui.QAction(MainWindow)
        self.actionSave_Golden_Orbit.setObjectName(_fromUtf8("actionSave_Golden_Orbit"))
        self.actionRead_BPMs_Corrs = QtGui.QAction(MainWindow)
        self.actionRead_BPMs_Corrs.setObjectName(_fromUtf8("actionRead_BPMs_Corrs"))
        self.actionCalculate_RM = QtGui.QAction(MainWindow)
        self.actionCalculate_RM.setObjectName(_fromUtf8("actionCalculate_RM"))
        self.actionCalculate_ORM = QtGui.QAction(MainWindow)
        self.actionCalculate_ORM.setObjectName(_fromUtf8("actionCalculate_ORM"))
        self.actionAdaptive_Feedback = QtGui.QAction(MainWindow)
        self.actionAdaptive_Feedback.setObjectName(_fromUtf8("actionAdaptive_Feedback"))
        self.actionLoad_GO_from_Orbit_Display = QtGui.QAction(MainWindow)
        self.actionLoad_GO_from_Orbit_Display.setObjectName(_fromUtf8("actionLoad_GO_from_Orbit_Display"))
        self.actionSave_corrs = QtGui.QAction(MainWindow)
        self.actionSave_corrs.setObjectName(_fromUtf8("actionSave_corrs"))
        self.actionLoad_corrs = QtGui.QAction(MainWindow)
        self.actionLoad_corrs.setObjectName(_fromUtf8("actionLoad_corrs"))
        self.mainToolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Controls", None))
        self.pb_statistics_start.setText(_translate("MainWindow", "Start Statistics", None))
        self.label_12.setText(_translate("MainWindow", "Number of Shots", None))
        self.label_7.setText(_translate("MainWindow", "Update rate", None))
        self.cb_disp.setText(_translate("MainWindow", "Show Dispersion", None))
        self.cb_sase.setText(_translate("MainWindow", "Show Orbit-SASE correlation", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Orbit Correlation", None))
        self.action_Parameters.setText(_translate("MainWindow", "Parameters", None))
        self.actionLoad_Golden_Orbit.setText(_translate("MainWindow", "Load Golden Orbit", None))
        self.actionSave_Golden_Orbit.setText(_translate("MainWindow", "Save Golden Orbit", None))
        self.actionRead_BPMs_Corrs.setText(_translate("MainWindow", "Read BPMs and Corrs", None))
        self.actionCalculate_RM.setText(_translate("MainWindow", "Calculate ORM and DRM", None))
        self.actionCalculate_ORM.setText(_translate("MainWindow", "Calculate ORM", None))
        self.actionAdaptive_Feedback.setText(_translate("MainWindow", "Adaptive Feedback", None))
        self.actionLoad_GO_from_Orbit_Display.setText(_translate("MainWindow", "Load GO from Orbit Display", None))
        self.actionSave_corrs.setText(_translate("MainWindow", "Save", None))
        self.actionLoad_corrs.setText(_translate("MainWindow", "Load", None))

