# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UImanul2.ui'
#
# Created: Fri Aug 25 10:10:28 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1222, 892)
        MainWindow.setMinimumSize(QtCore.QSize(1150, 0))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_30 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_26 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.gridLayout_27 = QtGui.QGridLayout()
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.pb_update_lat = QtGui.QPushButton(self.groupBox_5)
        self.pb_update_lat.setEnabled(True)
        self.pb_update_lat.setMinimumSize(QtCore.QSize(100, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pb_update_lat.setFont(font)
        self.pb_update_lat.setStyleSheet(_fromUtf8("color: rgb(85, 255, 127);"))
        self.pb_update_lat.setObjectName(_fromUtf8("pb_update_lat"))
        self.gridLayout_27.addWidget(self.pb_update_lat, 1, 0, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_27, 1, 1, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_5, 6, 3, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 128))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_24 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.gridLayout_25 = QtGui.QGridLayout()
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.pb_feedback = QtGui.QPushButton(self.groupBox_4)
        self.pb_feedback.setEnabled(True)
        self.pb_feedback.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pb_feedback.setFont(font)
        self.pb_feedback.setStyleSheet(_fromUtf8("color: rgb(85, 255, 127);"))
        self.pb_feedback.setObjectName(_fromUtf8("pb_feedback"))
        self.verticalLayout_12.addWidget(self.pb_feedback)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_24.addWidget(self.label_8)
        self.sb_feedback_sec = QtGui.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_feedback_sec.setFont(font)
        self.sb_feedback_sec.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_feedback_sec.setMinimum(1.0)
        self.sb_feedback_sec.setMaximum(30.0)
        self.sb_feedback_sec.setSingleStep(1.0)
        self.sb_feedback_sec.setProperty("value", 1.0)
        self.sb_feedback_sec.setObjectName(_fromUtf8("sb_feedback_sec"))
        self.horizontalLayout_24.addWidget(self.sb_feedback_sec)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        self.gridLayout_25.addLayout(self.verticalLayout_12, 2, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_30.addWidget(self.label_12)
        self.sb_apply_fraction = QtGui.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_apply_fraction.setFont(font)
        self.sb_apply_fraction.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_apply_fraction.setMinimum(0.0)
        self.sb_apply_fraction.setMaximum(1.0)
        self.sb_apply_fraction.setSingleStep(0.1)
        self.sb_apply_fraction.setProperty("value", 1.0)
        self.sb_apply_fraction.setObjectName(_fromUtf8("sb_apply_fraction"))
        self.horizontalLayout_30.addWidget(self.sb_apply_fraction)
        self.verticalLayout_3.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_23.addWidget(self.label_7)
        self.sb_alpha = QtGui.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_alpha.setFont(font)
        self.sb_alpha.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_alpha.setMinimum(0.0)
        self.sb_alpha.setMaximum(1.0)
        self.sb_alpha.setSingleStep(0.1)
        self.sb_alpha.setProperty("value", 0.0)
        self.sb_alpha.setObjectName(_fromUtf8("sb_alpha"))
        self.horizontalLayout_23.addWidget(self.sb_alpha)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.gridLayout_25.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_25, 0, 1, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_4, 6, 0, 1, 2)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_28 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.gridLayout_29 = QtGui.QGridLayout()
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.pb_set_golden = QtGui.QPushButton(self.groupBox_6)
        self.pb_set_golden.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_set_golden.setFont(font)
        self.pb_set_golden.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.pb_set_golden.setObjectName(_fromUtf8("pb_set_golden"))
        self.gridLayout_29.addWidget(self.pb_set_golden, 0, 0, 1, 1)
        self.pb_zero_gold = QtGui.QPushButton(self.groupBox_6)
        self.pb_zero_gold.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_zero_gold.setFont(font)
        self.pb_zero_gold.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.pb_zero_gold.setObjectName(_fromUtf8("pb_zero_gold"))
        self.gridLayout_29.addWidget(self.pb_zero_gold, 1, 0, 1, 1)
        self.pb_save_golden = QtGui.QPushButton(self.groupBox_6)
        self.pb_save_golden.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_save_golden.setFont(font)
        self.pb_save_golden.setObjectName(_fromUtf8("pb_save_golden"))
        self.gridLayout_29.addWidget(self.pb_save_golden, 0, 1, 1, 1)
        self.pb_load_golden = QtGui.QPushButton(self.groupBox_6)
        self.pb_load_golden.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_load_golden.setFont(font)
        self.pb_load_golden.setObjectName(_fromUtf8("pb_load_golden"))
        self.gridLayout_29.addWidget(self.pb_load_golden, 1, 1, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_29, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_6, 4, 3, 1, 1)
        self.w_orbit = QtGui.QWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_orbit.sizePolicy().hasHeightForWidth())
        self.w_orbit.setSizePolicy(sizePolicy)
        self.w_orbit.setMinimumSize(QtCore.QSize(650, 400))
        self.w_orbit.setStyleSheet(_fromUtf8(""))
        self.w_orbit.setObjectName(_fromUtf8("w_orbit"))
        self.gridLayout_30.addWidget(self.w_orbit, 1, 0, 1, 2)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pb_apply_kicks = QtGui.QPushButton(self.tab_2)
        self.pb_apply_kicks.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pb_apply_kicks.setFont(font)
        self.pb_apply_kicks.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.pb_apply_kicks.setObjectName(_fromUtf8("pb_apply_kicks"))
        self.verticalLayout_2.addWidget(self.pb_apply_kicks)
        self.horizontalLayout_25.addLayout(self.verticalLayout_2)
        self.pb_correct_orbit = QtGui.QPushButton(self.tab_2)
        self.pb_correct_orbit.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pb_correct_orbit.setFont(font)
        self.pb_correct_orbit.setStyleSheet(_fromUtf8("color: rgb(85, 255, 127);"))
        self.pb_correct_orbit.setObjectName(_fromUtf8("pb_correct_orbit"))
        self.horizontalLayout_25.addWidget(self.pb_correct_orbit)
        self.gridLayout_30.addLayout(self.horizontalLayout_25, 4, 0, 1, 2)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.cb_correction_result = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_correction_result.setFont(font)
        self.cb_correction_result.setChecked(True)
        self.cb_correction_result.setObjectName(_fromUtf8("cb_correction_result"))
        self.horizontalLayout_19.addWidget(self.cb_correction_result)
        self.pb_online_orbit = QtGui.QPushButton(self.tab_2)
        self.pb_online_orbit.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_online_orbit.setFont(font)
        self.pb_online_orbit.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.pb_online_orbit.setObjectName(_fromUtf8("pb_online_orbit"))
        self.horizontalLayout_19.addWidget(self.pb_online_orbit)
        self.pb_golden_orbit = QtGui.QPushButton(self.tab_2)
        self.pb_golden_orbit.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_golden_orbit.setFont(font)
        self.pb_golden_orbit.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.pb_golden_orbit.setObjectName(_fromUtf8("pb_golden_orbit"))
        self.horizontalLayout_19.addWidget(self.pb_golden_orbit)
        self.cb_close_orbit = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_close_orbit.setFont(font)
        self.cb_close_orbit.setChecked(True)
        self.cb_close_orbit.setObjectName(_fromUtf8("cb_close_orbit"))
        self.horizontalLayout_19.addWidget(self.cb_close_orbit)
        self.gridLayout_30.addLayout(self.horizontalLayout_19, 0, 0, 1, 1)
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_3.setMaximumSize(QtCore.QSize(420, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_22 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.w_cor = QtGui.QWidget(self.tab_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_cor.sizePolicy().hasHeightForWidth())
        self.w_cor.setSizePolicy(sizePolicy)
        self.w_cor.setMinimumSize(QtCore.QSize(450, 121))
        self.w_cor.setMaximumSize(QtCore.QSize(400, 16777215))
        self.w_cor.setObjectName(_fromUtf8("w_cor"))
        self.gridLayout_22.addWidget(self.w_cor, 1, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.pb_reset_all = QtGui.QPushButton(self.tab_8)
        self.pb_reset_all.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_reset_all.setFont(font)
        self.pb_reset_all.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.pb_reset_all.setObjectName(_fromUtf8("pb_reset_all"))
        self.horizontalLayout_20.addWidget(self.pb_reset_all)
        self.pb_check = QtGui.QPushButton(self.tab_8)
        self.pb_check.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_check.setFont(font)
        self.pb_check.setObjectName(_fromUtf8("pb_check"))
        self.horizontalLayout_20.addWidget(self.pb_check)
        self.pb_uncheck = QtGui.QPushButton(self.tab_8)
        self.pb_uncheck.setEnabled(True)
        self.pb_uncheck.setMinimumSize(QtCore.QSize(0, 20))
        self.pb_uncheck.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_uncheck.setFont(font)
        self.pb_uncheck.setStyleSheet(_fromUtf8(""))
        self.pb_uncheck.setObjectName(_fromUtf8("pb_uncheck"))
        self.horizontalLayout_20.addWidget(self.pb_uncheck)
        self.gridLayout_22.addLayout(self.horizontalLayout_20, 4, 0, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.cb_x_cors = QtGui.QCheckBox(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_x_cors.setFont(font)
        self.cb_x_cors.setObjectName(_fromUtf8("cb_x_cors"))
        self.horizontalLayout_21.addWidget(self.cb_x_cors)
        self.cb_y_cors = QtGui.QCheckBox(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_y_cors.setFont(font)
        self.cb_y_cors.setObjectName(_fromUtf8("cb_y_cors"))
        self.horizontalLayout_21.addWidget(self.cb_y_cors)
        self.pb_uncheck_red = QtGui.QPushButton(self.tab_8)
        self.pb_uncheck_red.setEnabled(True)
        self.pb_uncheck_red.setMinimumSize(QtCore.QSize(0, 20))
        self.pb_uncheck_red.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_uncheck_red.setFont(font)
        self.pb_uncheck_red.setStyleSheet(_fromUtf8(""))
        self.pb_uncheck_red.setObjectName(_fromUtf8("pb_uncheck_red"))
        self.horizontalLayout_21.addWidget(self.pb_uncheck_red)
        self.gridLayout_22.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tab_9)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.w_bpm = QtGui.QWidget(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_bpm.sizePolicy().hasHeightForWidth())
        self.w_bpm.setSizePolicy(sizePolicy)
        self.w_bpm.setMinimumSize(QtCore.QSize(400, 300))
        self.w_bpm.setObjectName(_fromUtf8("w_bpm"))
        self.gridLayout_23.addWidget(self.w_bpm, 0, 1, 1, 1)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.pb_bpm_check = QtGui.QPushButton(self.tab_9)
        self.pb_bpm_check.setObjectName(_fromUtf8("pb_bpm_check"))
        self.horizontalLayout_22.addWidget(self.pb_bpm_check)
        self.pb_bpm_uncheck = QtGui.QPushButton(self.tab_9)
        self.pb_bpm_uncheck.setObjectName(_fromUtf8("pb_bpm_uncheck"))
        self.horizontalLayout_22.addWidget(self.pb_bpm_uncheck)
        self.gridLayout_23.addLayout(self.horizontalLayout_22, 1, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_9, _fromUtf8(""))
        self.gridLayout_30.addWidget(self.tabWidget_3, 0, 3, 4, 1)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_32.addWidget(self.label)
        self.sb_lat_from = QtGui.QDoubleSpinBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_lat_from.setFont(font)
        self.sb_lat_from.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_lat_from.setMinimum(23.2)
        self.sb_lat_from.setMaximum(2500.0)
        self.sb_lat_from.setSingleStep(50.0)
        self.sb_lat_from.setProperty("value", 23.2)
        self.sb_lat_from.setObjectName(_fromUtf8("sb_lat_from"))
        self.horizontalLayout_32.addWidget(self.sb_lat_from)
        self.cb_lattice = QtGui.QComboBox(self.tab_2)
        self.cb_lattice.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_lattice.setFont(font)
        self.cb_lattice.setObjectName(_fromUtf8("cb_lattice"))
        self.horizontalLayout_32.addWidget(self.cb_lattice)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_32.addWidget(self.label_2)
        self.sb_lat_to = QtGui.QDoubleSpinBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_lat_to.setFont(font)
        self.sb_lat_to.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_lat_to.setMinimum(23.2)
        self.sb_lat_to.setMaximum(2500.0)
        self.sb_lat_to.setSingleStep(50.0)
        self.sb_lat_to.setProperty("value", 60.0)
        self.sb_lat_to.setObjectName(_fromUtf8("sb_lat_to"))
        self.horizontalLayout_32.addWidget(self.sb_lat_to)
        self.pb_set_pos = QtGui.QPushButton(self.tab_2)
        self.pb_set_pos.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_set_pos.setFont(font)
        self.pb_set_pos.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.pb_set_pos.setObjectName(_fromUtf8("pb_set_pos"))
        self.horizontalLayout_32.addWidget(self.pb_set_pos)
        self.gridLayout_30.addLayout(self.horizontalLayout_32, 2, 0, 1, 2)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.w_disp = QtGui.QWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_disp.sizePolicy().hasHeightForWidth())
        self.w_disp.setSizePolicy(sizePolicy)
        self.w_disp.setMinimumSize(QtCore.QSize(650, 400))
        self.w_disp.setStyleSheet(_fromUtf8(""))
        self.w_disp.setObjectName(_fromUtf8("w_disp"))
        self.gridLayout_2.addWidget(self.w_disp, 0, 0, 1, 2)
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 144))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_34 = QtGui.QGridLayout()
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.cb_cav_list = QtGui.QComboBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_cav_list.sizePolicy().hasHeightForWidth())
        self.cb_cav_list.setSizePolicy(sizePolicy)
        self.cb_cav_list.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_cav_list.setFont(font)
        self.cb_cav_list.setObjectName(_fromUtf8("cb_cav_list"))
        self.gridLayout_34.addWidget(self.cb_cav_list, 1, 0, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_9 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_26.addWidget(self.label_9)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem)
        self.sb_voltage = QtGui.QDoubleSpinBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_voltage.sizePolicy().hasHeightForWidth())
        self.sb_voltage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_voltage.setFont(font)
        self.sb_voltage.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_voltage.setMinimum(-20.0)
        self.sb_voltage.setMaximum(20.0)
        self.sb_voltage.setSingleStep(0.5)
        self.sb_voltage.setProperty("value", 0.0)
        self.sb_voltage.setObjectName(_fromUtf8("sb_voltage"))
        self.horizontalLayout_26.addWidget(self.sb_voltage)
        self.gridLayout_34.addLayout(self.horizontalLayout_26, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_34, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_8, 2, 0, 1, 1)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.gridLayout_2.addLayout(self.horizontalLayout_28, 4, 0, 1, 2)
        self.pb_start_meas = QtGui.QPushButton(self.tab)
        self.pb_start_meas.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pb_start_meas.setFont(font)
        self.pb_start_meas.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.pb_start_meas.setObjectName(_fromUtf8("pb_start_meas"))
        self.gridLayout_2.addWidget(self.pb_start_meas, 3, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_31 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_13 = QtGui.QLabel(self.groupBox_7)
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_31.addWidget(self.label_13)
        self.sb_n_steps = QtGui.QSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_n_steps.setFont(font)
        self.sb_n_steps.setMinimum(1)
        self.sb_n_steps.setMaximum(5)
        self.sb_n_steps.setProperty("value", 1)
        self.sb_n_steps.setObjectName(_fromUtf8("sb_n_steps"))
        self.horizontalLayout_31.addWidget(self.sb_n_steps)
        self.gridLayout_31.addLayout(self.horizontalLayout_31, 0, 1, 1, 1)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_11 = QtGui.QLabel(self.groupBox_7)
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_29.addWidget(self.label_11)
        self.sb_time_delay = QtGui.QDoubleSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_time_delay.setFont(font)
        self.sb_time_delay.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_time_delay.setDecimals(1)
        self.sb_time_delay.setMinimum(0.0)
        self.sb_time_delay.setMaximum(10.0)
        self.sb_time_delay.setSingleStep(1.0)
        self.sb_time_delay.setProperty("value", 2.0)
        self.sb_time_delay.setObjectName(_fromUtf8("sb_time_delay"))
        self.horizontalLayout_29.addWidget(self.sb_time_delay)
        self.gridLayout_31.addLayout(self.horizontalLayout_29, 1, 1, 1, 1)
        self.gridLayout_32 = QtGui.QGridLayout()
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_10 = QtGui.QLabel(self.groupBox_7)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_27.addWidget(self.label_10)
        self.sb_n_readings = QtGui.QSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_n_readings.setFont(font)
        self.sb_n_readings.setMinimum(1)
        self.sb_n_readings.setMaximum(30)
        self.sb_n_readings.setProperty("value", 10)
        self.sb_n_readings.setObjectName(_fromUtf8("sb_n_readings"))
        self.horizontalLayout_27.addWidget(self.sb_n_readings)
        self.verticalLayout_14.addLayout(self.horizontalLayout_27)
        self.gridLayout_32.addLayout(self.verticalLayout_14, 2, 1, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_32, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_7, 2, 1, 2, 1)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.widget_2 = QtGui.QWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(700, 400))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_6.addWidget(self.widget_2, 0, 0, 1, 2)
        self.widget = QtGui.QWidget(self.tab_4)
        self.widget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(400, 200))
        self.widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_6.addWidget(self.widget, 0, 2, 1, 2)
        self.pb_update = QtGui.QPushButton(self.tab_4)
        self.pb_update.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_update.setFont(font)
        self.pb_update.setObjectName(_fromUtf8("pb_update"))
        self.gridLayout_6.addWidget(self.pb_update, 3, 2, 1, 2)
        self.pb_reset = QtGui.QPushButton(self.tab_4)
        self.pb_reset.setEnabled(True)
        self.pb_reset.setMinimumSize(QtCore.QSize(0, 20))
        self.pb_reset.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_reset.setFont(font)
        self.pb_reset.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.pb_reset.setObjectName(_fromUtf8("pb_reset"))
        self.gridLayout_6.addWidget(self.pb_reset, 2, 2, 1, 2)
        self.pb_read = QtGui.QPushButton(self.tab_4)
        self.pb_read.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pb_read.setFont(font)
        self.pb_read.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.pb_read.setObjectName(_fromUtf8("pb_read"))
        self.gridLayout_6.addWidget(self.pb_read, 2, 1, 2, 1)
        self.pb_write = QtGui.QPushButton(self.tab_4)
        self.pb_write.setEnabled(False)
        self.pb_write.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pb_write.setFont(font)
        self.pb_write.setStyleSheet(_fromUtf8("color: rgb(85, 255, 127);"))
        self.pb_write.setObjectName(_fromUtf8("pb_write"))
        self.gridLayout_6.addWidget(self.pb_write, 2, 0, 2, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 140))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cb_otr55 = QtGui.QCheckBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_otr55.setFont(font)
        self.cb_otr55.setChecked(True)
        self.cb_otr55.setObjectName(_fromUtf8("cb_otr55"))
        self.verticalLayout.addWidget(self.cb_otr55)
        self.cb_otr218 = QtGui.QCheckBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_otr218.setFont(font)
        self.cb_otr218.setObjectName(_fromUtf8("cb_otr218"))
        self.verticalLayout.addWidget(self.cb_otr218)
        self.cb_otr450 = QtGui.QCheckBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_otr450.setFont(font)
        self.cb_otr450.setObjectName(_fromUtf8("cb_otr450"))
        self.verticalLayout.addWidget(self.cb_otr450)
        self.horizontalLayout_13.addLayout(self.verticalLayout)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.cb_design_tws = QtGui.QCheckBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_design_tws.setFont(font)
        self.cb_design_tws.setObjectName(_fromUtf8("cb_design_tws"))
        self.verticalLayout_10.addWidget(self.cb_design_tws)
        self.horizontalLayout_13.addLayout(self.verticalLayout_10)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.gridLayout_6.addWidget(self.groupBox_10, 1, 0, 1, 2)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.cb_sec_order = QtGui.QCheckBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_sec_order.setFont(font)
        self.cb_sec_order.setObjectName(_fromUtf8("cb_sec_order"))
        self.gridLayout_14.addWidget(self.cb_sec_order, 0, 0, 1, 1)
        self.cb_coupler_kick = QtGui.QCheckBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_coupler_kick.setFont(font)
        self.cb_coupler_kick.setObjectName(_fromUtf8("cb_coupler_kick"))
        self.gridLayout_14.addWidget(self.cb_coupler_kick, 1, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_9, 1, 2, 1, 2)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.tabWidget_2)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1222, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuGolden_Orbit = QtGui.QMenu(self.menuBar)
        self.menuGolden_Orbit.setObjectName(_fromUtf8("menuGolden_Orbit"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.action_Parameters = QtGui.QAction(MainWindow)
        self.action_Parameters.setObjectName(_fromUtf8("action_Parameters"))
        self.actionLoad_Golden_Orbit = QtGui.QAction(MainWindow)
        self.actionLoad_Golden_Orbit.setObjectName(_fromUtf8("actionLoad_Golden_Orbit"))
        self.actionSave_Golden_Orbit = QtGui.QAction(MainWindow)
        self.actionSave_Golden_Orbit.setObjectName(_fromUtf8("actionSave_Golden_Orbit"))
        self.actionRead_BPMs_Corrs = QtGui.QAction(MainWindow)
        self.actionRead_BPMs_Corrs.setObjectName(_fromUtf8("actionRead_BPMs_Corrs"))
        self.actionCalculate_RM = QtGui.QAction(MainWindow)
        self.actionCalculate_RM.setObjectName(_fromUtf8("actionCalculate_RM"))
        self.actionCalculate_ORM = QtGui.QAction(MainWindow)
        self.actionCalculate_ORM.setObjectName(_fromUtf8("actionCalculate_ORM"))
        self.actionAdaptive_Feedback = QtGui.QAction(MainWindow)
        self.actionAdaptive_Feedback.setObjectName(_fromUtf8("actionAdaptive_Feedback"))
        self.actionLoad_GO_from_Orbit_Display = QtGui.QAction(MainWindow)
        self.actionLoad_GO_from_Orbit_Display.setObjectName(_fromUtf8("actionLoad_GO_from_Orbit_Display"))
        self.menu_File.addAction(self.action_Parameters)
        self.menu_File.addAction(self.actionCalculate_ORM)
        self.menu_File.addAction(self.actionCalculate_RM)
        self.menu_File.addAction(self.actionRead_BPMs_Corrs)
        self.menu_File.addAction(self.actionAdaptive_Feedback)
        self.menuGolden_Orbit.addAction(self.actionLoad_Golden_Orbit)
        self.menuGolden_Orbit.addAction(self.actionSave_Golden_Orbit)
        self.menuGolden_Orbit.addAction(self.actionLoad_GO_from_Orbit_Display)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuGolden_Orbit.menuAction())
        self.mainToolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cb_otr55, self.cb_otr218)
        MainWindow.setTabOrder(self.cb_otr218, self.cb_otr450)
        MainWindow.setTabOrder(self.cb_otr450, self.cb_design_tws)
        MainWindow.setTabOrder(self.cb_design_tws, self.pb_write)
        MainWindow.setTabOrder(self.pb_write, self.pb_read)
        MainWindow.setTabOrder(self.pb_read, self.pb_reset)
        MainWindow.setTabOrder(self.pb_reset, self.pb_update)
        MainWindow.setTabOrder(self.pb_update, self.cb_sec_order)
        MainWindow.setTabOrder(self.cb_sec_order, self.cb_coupler_kick)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Lattice", None))
        self.pb_update_lat.setText(_translate("MainWindow", "Update Lattice DOOCS", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Controls", None))
        self.pb_feedback.setText(_translate("MainWindow", "Orbit Keeper On", None))
        self.label_8.setText(_translate("MainWindow", " Repeat in sec", None))
        self.label_12.setText(_translate("MainWindow", "Apply fraction             ", None))
        self.label_7.setText(_translate("MainWindow", "alpha (0-orbit. 1-disp)", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Golden Orbit", None))
        self.pb_set_golden.setText(_translate("MainWindow", "Set Golden Orbit", None))
        self.pb_zero_gold.setText(_translate("MainWindow", "Zero Golden Orbit", None))
        self.pb_save_golden.setText(_translate("MainWindow", "Save Golden Orbit", None))
        self.pb_load_golden.setText(_translate("MainWindow", "Load Golden Orbit", None))
        self.pb_apply_kicks.setText(_translate("MainWindow", "Apply Kicks", None))
        self.pb_correct_orbit.setText(_translate("MainWindow", "Calculate Correction", None))
        self.cb_correction_result.setText(_translate("MainWindow", "Correction Result / Changes", None))
        self.pb_online_orbit.setText(_translate("MainWindow", "Live Orbit On", None))
        self.pb_golden_orbit.setText(_translate("MainWindow", "Show Golden Orbit", None))
        self.cb_close_orbit.setText(_translate("MainWindow", "Close Orbit", None))
        self.pb_reset_all.setText(_translate("MainWindow", "Undo (0)", None))
        self.pb_check.setText(_translate("MainWindow", "Check", None))
        self.pb_uncheck.setText(_translate("MainWindow", "Uncheck", None))
        self.cb_x_cors.setText(_translate("MainWindow", "X", None))
        self.cb_y_cors.setText(_translate("MainWindow", "Y", None))
        self.pb_uncheck_red.setText(_translate("MainWindow", "Uncheck Red", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Correctors", None))
        self.pb_bpm_check.setText(_translate("MainWindow", "Check", None))
        self.pb_bpm_uncheck.setText(_translate("MainWindow", "Uncheck", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "BPMs", None))
        self.label.setText(_translate("MainWindow", "From", None))
        self.label_2.setText(_translate("MainWindow", "To", None))
        self.pb_set_pos.setText(_translate("MainWindow", "Set Positions", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Orbit Correction", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Cavity Controls", None))
        self.label_9.setText(_translate("MainWindow", "Voltage Changes [MeV]", None))
        self.pb_start_meas.setText(_translate("MainWindow", "Start Measurement", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Expert Controls", None))
        self.label_13.setText(_translate("MainWindow", "Number of steps", None))
        self.label_11.setText(_translate("MainWindow", "Time delay", None))
        self.label_10.setText(_translate("MainWindow", "Number of BPM readings", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Dispersion Measurement", None))
        self.pb_update.setText(_translate("MainWindow", "Update Reference", None))
        self.pb_reset.setText(_translate("MainWindow", "Reset All", None))
        self.pb_read.setText(_translate("MainWindow", "Read from Quads", None))
        self.pb_write.setText(_translate("MainWindow", "Write to Quads", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "BackTracking", None))
        self.cb_otr55.setText(_translate("MainWindow", "OTRC 55", None))
        self.cb_otr218.setText(_translate("MainWindow", "OTRB 218", None))
        self.cb_otr450.setText(_translate("MainWindow", "OTRB 450", None))
        self.cb_design_tws.setText(_translate("MainWindow", "Design Twiss", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Calc Options", None))
        self.cb_sec_order.setText(_translate("MainWindow", "Second Order", None))
        self.cb_coupler_kick.setText(_translate("MainWindow", "Coupler Kick", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Twiss Monitor", None))
        self.menu_File.setTitle(_translate("MainWindow", "&Expert Panel", None))
        self.menuGolden_Orbit.setTitle(_translate("MainWindow", "Golden Orbit", None))
        self.action_Parameters.setText(_translate("MainWindow", "Parameters", None))
        self.actionLoad_Golden_Orbit.setText(_translate("MainWindow", "Load Golden Orbit", None))
        self.actionSave_Golden_Orbit.setText(_translate("MainWindow", "Save Golden Orbit", None))
        self.actionRead_BPMs_Corrs.setText(_translate("MainWindow", "Read BPMs and Corrs", None))
        self.actionCalculate_RM.setText(_translate("MainWindow", "Calculate ORM and DRM", None))
        self.actionCalculate_ORM.setText(_translate("MainWindow", "Calculate ORM", None))
        self.actionAdaptive_Feedback.setText(_translate("MainWindow", "Adaptive Feedback", None))
        self.actionLoad_GO_from_Orbit_Display.setText(_translate("MainWindow", "Load GO from Orbit Display", None))

