# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UImanul2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1159, 828)
        MainWindow.setMinimumSize(QtCore.QSize(1150, 0))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(7)
        self.gridLayout_5.setVerticalSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_3 = QtWidgets.QWidget(self.tab_2)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pb_ref_orb = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_ref_orb.setFont(font)
        self.pb_ref_orb.setStyleSheet("color: rgb(255, 0, 0);")
        self.pb_ref_orb.setObjectName("pb_ref_orb")
        self.horizontalLayout_19.addWidget(self.pb_ref_orb)
        self.pb_calc_orb = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_calc_orb.setFont(font)
        self.pb_calc_orb.setStyleSheet("color: rgb(255, 0, 0);")
        self.pb_calc_orb.setObjectName("pb_calc_orb")
        self.horizontalLayout_19.addWidget(self.pb_calc_orb)
        self.pb_online_orbit = QtWidgets.QPushButton(self.widget_3)
        self.pb_online_orbit.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_online_orbit.setFont(font)
        self.pb_online_orbit.setStyleSheet("color: rgb(85, 255, 255);")
        self.pb_online_orbit.setObjectName("pb_online_orbit")
        self.horizontalLayout_19.addWidget(self.pb_online_orbit)
        self.pb_golden_orbit = QtWidgets.QPushButton(self.widget_3)
        self.pb_golden_orbit.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_golden_orbit.setFont(font)
        self.pb_golden_orbit.setStyleSheet("color: rgb(85, 255, 255);")
        self.pb_golden_orbit.setObjectName("pb_golden_orbit")
        self.horizontalLayout_19.addWidget(self.pb_golden_orbit)
        self.cb_close_orbit = QtWidgets.QCheckBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_close_orbit.setFont(font)
        self.cb_close_orbit.setChecked(False)
        self.cb_close_orbit.setObjectName("cb_close_orbit")
        self.horizontalLayout_19.addWidget(self.cb_close_orbit)
        self.pb_reset_all = QtWidgets.QPushButton(self.widget_3)
        self.pb_reset_all.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_reset_all.setFont(font)
        self.pb_reset_all.setStyleSheet("color: rgb(255, 0, 0);")
        self.pb_reset_all.setObjectName("pb_reset_all")
        self.horizontalLayout_19.addWidget(self.pb_reset_all)
        self.pb_hide_show_dev_panel = QtWidgets.QPushButton(self.widget_3)
        self.pb_hide_show_dev_panel.setStyleSheet("color: rgb(255, 0, 255);")
        self.pb_hide_show_dev_panel.setObjectName("pb_hide_show_dev_panel")
        self.horizontalLayout_19.addWidget(self.pb_hide_show_dev_panel)
        self.gridLayout.addLayout(self.horizontalLayout_19, 0, 0, 1, 1)
        self.w_orbit = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_orbit.sizePolicy().hasHeightForWidth())
        self.w_orbit.setSizePolicy(sizePolicy)
        self.w_orbit.setMinimumSize(QtCore.QSize(650, 360))
        self.w_orbit.setStyleSheet("")
        self.w_orbit.setObjectName("w_orbit")
        self.gridLayout.addWidget(self.w_orbit, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_3, 6, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.tab_2)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_24.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_24.setHorizontalSpacing(7)
        self.gridLayout_24.setVerticalSpacing(1)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.sb_apply_fraction = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_apply_fraction.setFont(font)
        self.sb_apply_fraction.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_apply_fraction.setMinimum(0.0)
        self.sb_apply_fraction.setMaximum(1.0)
        self.sb_apply_fraction.setSingleStep(0.1)
        self.sb_apply_fraction.setProperty("value", 0.8)
        self.sb_apply_fraction.setObjectName("sb_apply_fraction")
        self.gridLayout_24.addWidget(self.sb_apply_fraction, 0, 1, 1, 1)
        self.sb_alpha = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_alpha.setFont(font)
        self.sb_alpha.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_alpha.setMinimum(0.0)
        self.sb_alpha.setMaximum(1.0)
        self.sb_alpha.setSingleStep(0.1)
        self.sb_alpha.setProperty("value", 0.0)
        self.sb_alpha.setObjectName("sb_alpha")
        self.gridLayout_24.addWidget(self.sb_alpha, 2, 1, 1, 1)
        self.pb_feedback = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_feedback.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_feedback.sizePolicy().hasHeightForWidth())
        self.pb_feedback.setSizePolicy(sizePolicy)
        self.pb_feedback.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_feedback.setFont(font)
        self.pb_feedback.setStyleSheet("color: rgb(85, 255, 127); font-size: 14pt;")
        self.pb_feedback.setObjectName("pb_feedback")
        self.gridLayout_24.addWidget(self.pb_feedback, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_24.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_24.addWidget(self.label_12, 0, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_24.addWidget(self.label_8)
        self.sb_feedback_sec = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_feedback_sec.setFont(font)
        self.sb_feedback_sec.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_feedback_sec.setMinimum(1.0)
        self.sb_feedback_sec.setMaximum(30.0)
        self.sb_feedback_sec.setSingleStep(1.0)
        self.sb_feedback_sec.setProperty("value", 2.0)
        self.sb_feedback_sec.setObjectName("sb_feedback_sec")
        self.horizontalLayout_24.addWidget(self.sb_feedback_sec)
        self.gridLayout_24.addLayout(self.horizontalLayout_24, 2, 3, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_4, 1, 0, 1, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setVerticalSpacing(3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pb_apply_kicks = QtWidgets.QPushButton(self.widget_4)
        self.pb_apply_kicks.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pb_apply_kicks.setFont(font)
        self.pb_apply_kicks.setStyleSheet("color: rgb(255, 0, 0); font-size: 18pt;")
        self.pb_apply_kicks.setObjectName("pb_apply_kicks")
        self.gridLayout_4.addWidget(self.pb_apply_kicks, 4, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.widget_4)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.sb_lat_from = QtWidgets.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_lat_from.setFont(font)
        self.sb_lat_from.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_lat_from.setMinimum(23.2)
        self.sb_lat_from.setMaximum(2500.0)
        self.sb_lat_from.setSingleStep(50.0)
        self.sb_lat_from.setProperty("value", 23.2)
        self.sb_lat_from.setObjectName("sb_lat_from")
        self.horizontalLayout_5.addWidget(self.sb_lat_from)
        self.cb_lattice = QtWidgets.QComboBox(self.frame)
        self.cb_lattice.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_lattice.setFont(font)
        self.cb_lattice.setObjectName("cb_lattice")
        self.horizontalLayout_5.addWidget(self.cb_lattice)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.sb_lat_to = QtWidgets.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_lat_to.setFont(font)
        self.sb_lat_to.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_lat_to.setMinimum(23.2)
        self.sb_lat_to.setMaximum(2500.0)
        self.sb_lat_to.setSingleStep(50.0)
        self.sb_lat_to.setProperty("value", 60.0)
        self.sb_lat_to.setObjectName("sb_lat_to")
        self.horizontalLayout_5.addWidget(self.sb_lat_to)
        self.pb_set_pos = QtWidgets.QPushButton(self.frame)
        self.pb_set_pos.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_set_pos.setFont(font)
        self.pb_set_pos.setStyleSheet("color: rgb(85, 255, 255);")
        self.pb_set_pos.setObjectName("pb_set_pos")
        self.horizontalLayout_5.addWidget(self.pb_set_pos)
        self.gridLayout_4.addWidget(self.frame, 2, 0, 1, 2)
        self.pb_correct_orbit = QtWidgets.QPushButton(self.widget_4)
        self.pb_correct_orbit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pb_correct_orbit.setFont(font)
        self.pb_correct_orbit.setStyleSheet("color: rgb(85, 255, 127); font-size: 18pt;")
        self.pb_correct_orbit.setObjectName("pb_correct_orbit")
        self.gridLayout_4.addWidget(self.pb_correct_orbit, 4, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 0, 0, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_26.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_26.setSpacing(6)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.combo_subtrain = QtWidgets.QComboBox(self.groupBox_5)
        self.combo_subtrain.setObjectName("combo_subtrain")
        self.horizontalLayout.addWidget(self.combo_subtrain)
        self.gridLayout_26.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.pb_update_lat = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_update_lat.setEnabled(True)
        self.pb_update_lat.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_update_lat.setFont(font)
        self.pb_update_lat.setStyleSheet("color: rgb(85, 255, 127); font-size: 14pt;")
        self.pb_update_lat.setObjectName("pb_update_lat")
        self.gridLayout_26.addWidget(self.pb_update_lat, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 1, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_11 = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox_11.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_40.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_40.setHorizontalSpacing(6)
        self.gridLayout_40.setVerticalSpacing(7)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.pb_read_orbit = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_read_orbit.sizePolicy().hasHeightForWidth())
        self.pb_read_orbit.setSizePolicy(sizePolicy)
        self.pb_read_orbit.setMinimumSize(QtCore.QSize(0, 0))
        self.pb_read_orbit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pb_read_orbit.setFont(font)
        self.pb_read_orbit.setStyleSheet("color: rgb(255, 0, 0); font-size: 14pt;")
        self.pb_read_orbit.setObjectName("pb_read_orbit")
        self.gridLayout_40.addWidget(self.pb_read_orbit, 0, 0, 1, 1)
        self.pb_calculate = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_calculate.sizePolicy().hasHeightForWidth())
        self.pb_calculate.setSizePolicy(sizePolicy)
        self.pb_calculate.setMinimumSize(QtCore.QSize(0, 0))
        self.pb_calculate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_calculate.setFont(font)
        self.pb_calculate.setStyleSheet("color: rgb(85, 255, 127); font-size: 14pt;")
        self.pb_calculate.setObjectName("pb_calculate")
        self.gridLayout_40.addWidget(self.pb_calculate, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_11)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_28.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_28.setSpacing(6)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.pb_set_golden = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_set_golden.sizePolicy().hasHeightForWidth())
        self.pb_set_golden.setSizePolicy(sizePolicy)
        self.pb_set_golden.setMinimumSize(QtCore.QSize(0, 0))
        self.pb_set_golden.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pb_set_golden.setFont(font)
        self.pb_set_golden.setStyleSheet("color: rgb(255, 0, 0); font-size: 14pt;")
        self.pb_set_golden.setObjectName("pb_set_golden")
        self.gridLayout_28.addWidget(self.pb_set_golden, 0, 0, 1, 1)
        self.pb_zero_gold = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_zero_gold.sizePolicy().hasHeightForWidth())
        self.pb_zero_gold.setSizePolicy(sizePolicy)
        self.pb_zero_gold.setMinimumSize(QtCore.QSize(0, 0))
        self.pb_zero_gold.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_zero_gold.setFont(font)
        self.pb_zero_gold.setStyleSheet("color: rgb(85, 255, 255); font-size: 14pt;")
        self.pb_zero_gold.setObjectName("pb_zero_gold")
        self.gridLayout_28.addWidget(self.pb_zero_gold, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 0, 3, 1, 1)
        self.gridLayout_5.addWidget(self.widget_4, 7, 0, 1, 2)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_3.setMaximumSize(QtCore.QSize(420, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setSpacing(6)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.w_cor = QtWidgets.QWidget(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_cor.sizePolicy().hasHeightForWidth())
        self.w_cor.setSizePolicy(sizePolicy)
        self.w_cor.setMinimumSize(QtCore.QSize(450, 121))
        self.w_cor.setMaximumSize(QtCore.QSize(400, 16777215))
        self.w_cor.setObjectName("w_cor")
        self.gridLayout_22.addWidget(self.w_cor, 2, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pb_check = QtWidgets.QPushButton(self.tab_8)
        self.pb_check.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_check.setFont(font)
        self.pb_check.setObjectName("pb_check")
        self.horizontalLayout_20.addWidget(self.pb_check)
        self.pb_uncheck = QtWidgets.QPushButton(self.tab_8)
        self.pb_uncheck.setEnabled(True)
        self.pb_uncheck.setMinimumSize(QtCore.QSize(0, 20))
        self.pb_uncheck.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_uncheck.setFont(font)
        self.pb_uncheck.setStyleSheet("")
        self.pb_uncheck.setObjectName("pb_uncheck")
        self.horizontalLayout_20.addWidget(self.pb_uncheck)
        self.gridLayout_22.addLayout(self.horizontalLayout_20, 5, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.cb_x_cors = QtWidgets.QCheckBox(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_x_cors.setFont(font)
        self.cb_x_cors.setChecked(True)
        self.cb_x_cors.setObjectName("cb_x_cors")
        self.horizontalLayout_21.addWidget(self.cb_x_cors)
        self.cb_y_cors = QtWidgets.QCheckBox(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_y_cors.setFont(font)
        self.cb_y_cors.setChecked(True)
        self.cb_y_cors.setObjectName("cb_y_cors")
        self.horizontalLayout_21.addWidget(self.cb_y_cors)
        self.cb_caxy = QtWidgets.QCheckBox(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_caxy.setFont(font)
        self.cb_caxy.setChecked(False)
        self.cb_caxy.setObjectName("cb_caxy")
        self.horizontalLayout_21.addWidget(self.cb_caxy)
        self.cb_cbxy = QtWidgets.QCheckBox(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_cbxy.setFont(font)
        self.cb_cbxy.setChecked(False)
        self.cb_cbxy.setObjectName("cb_cbxy")
        self.horizontalLayout_21.addWidget(self.cb_cbxy)
        self.gridLayout_22.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_23.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_23.setSpacing(6)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.w_bpm = QtWidgets.QWidget(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_bpm.sizePolicy().hasHeightForWidth())
        self.w_bpm.setSizePolicy(sizePolicy)
        self.w_bpm.setMinimumSize(QtCore.QSize(400, 300))
        self.w_bpm.setObjectName("w_bpm")
        self.gridLayout_23.addWidget(self.w_bpm, 0, 1, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.pb_bpm_check = QtWidgets.QPushButton(self.tab_9)
        self.pb_bpm_check.setObjectName("pb_bpm_check")
        self.horizontalLayout_22.addWidget(self.pb_bpm_check)
        self.pb_bpm_uncheck = QtWidgets.QPushButton(self.tab_9)
        self.pb_bpm_uncheck.setObjectName("pb_bpm_uncheck")
        self.horizontalLayout_22.addWidget(self.pb_bpm_uncheck)
        self.gridLayout_23.addLayout(self.horizontalLayout_22, 1, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.gridLayout_5.addWidget(self.tabWidget_3, 6, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.w_disp = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_disp.sizePolicy().hasHeightForWidth())
        self.w_disp.setSizePolicy(sizePolicy)
        self.w_disp.setMinimumSize(QtCore.QSize(650, 400))
        self.w_disp.setStyleSheet("")
        self.w_disp.setObjectName("w_disp")
        self.gridLayout_2.addWidget(self.w_disp, 0, 0, 1, 2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 144))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setSpacing(6)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.cb_cav_list = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_cav_list.sizePolicy().hasHeightForWidth())
        self.cb_cav_list.setSizePolicy(sizePolicy)
        self.cb_cav_list.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_cav_list.setFont(font)
        self.cb_cav_list.setObjectName("cb_cav_list")
        self.gridLayout_34.addWidget(self.cb_cav_list, 1, 0, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(6)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_9 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_26.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem)
        self.sb_voltage = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_voltage.sizePolicy().hasHeightForWidth())
        self.sb_voltage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_voltage.setFont(font)
        self.sb_voltage.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_voltage.setMinimum(-20.0)
        self.sb_voltage.setMaximum(20.0)
        self.sb_voltage.setSingleStep(0.5)
        self.sb_voltage.setProperty("value", 0.0)
        self.sb_voltage.setObjectName("sb_voltage")
        self.horizontalLayout_26.addWidget(self.sb_voltage)
        self.gridLayout_34.addLayout(self.horizontalLayout_26, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_34, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_8, 2, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_31.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_31.setSpacing(6)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setSpacing(6)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_31.addWidget(self.label_13)
        self.sb_n_steps = QtWidgets.QSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_n_steps.setFont(font)
        self.sb_n_steps.setMinimum(1)
        self.sb_n_steps.setMaximum(5)
        self.sb_n_steps.setProperty("value", 1)
        self.sb_n_steps.setObjectName("sb_n_steps")
        self.horizontalLayout_31.addWidget(self.sb_n_steps)
        self.gridLayout_31.addLayout(self.horizontalLayout_31, 0, 1, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSpacing(6)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_29.addWidget(self.label_11)
        self.sb_time_delay = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_time_delay.setFont(font)
        self.sb_time_delay.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_time_delay.setDecimals(1)
        self.sb_time_delay.setMinimum(0.0)
        self.sb_time_delay.setMaximum(10.0)
        self.sb_time_delay.setSingleStep(1.0)
        self.sb_time_delay.setProperty("value", 2.0)
        self.sb_time_delay.setObjectName("sb_time_delay")
        self.horizontalLayout_29.addWidget(self.sb_time_delay)
        self.gridLayout_31.addLayout(self.horizontalLayout_29, 1, 1, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSpacing(6)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_27.addWidget(self.label_10)
        self.sb_n_readings = QtWidgets.QSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_n_readings.setFont(font)
        self.sb_n_readings.setMinimum(1)
        self.sb_n_readings.setMaximum(30)
        self.sb_n_readings.setProperty("value", 10)
        self.sb_n_readings.setObjectName("sb_n_readings")
        self.horizontalLayout_27.addWidget(self.sb_n_readings)
        self.gridLayout_31.addLayout(self.horizontalLayout_27, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_7, 2, 1, 2, 1)
        self.pb_start_meas = QtWidgets.QPushButton(self.tab)
        self.pb_start_meas.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pb_start_meas.setFont(font)
        self.pb_start_meas.setStyleSheet("color: rgb(255, 0, 0);")
        self.pb_start_meas.setObjectName("pb_start_meas")
        self.gridLayout_2.addWidget(self.pb_start_meas, 3, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_2 = QtWidgets.QWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(700, 400))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6.addWidget(self.widget_2, 0, 0, 1, 2)
        self.widget = QtWidgets.QWidget(self.tab_4)
        self.widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(400, 200))
        self.widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout_6.addWidget(self.widget, 0, 2, 1, 2)
        self.pb_update = QtWidgets.QPushButton(self.tab_4)
        self.pb_update.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_update.setFont(font)
        self.pb_update.setObjectName("pb_update")
        self.gridLayout_6.addWidget(self.pb_update, 3, 2, 1, 2)
        self.pb_reset = QtWidgets.QPushButton(self.tab_4)
        self.pb_reset.setEnabled(True)
        self.pb_reset.setMinimumSize(QtCore.QSize(0, 20))
        self.pb_reset.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_reset.setFont(font)
        self.pb_reset.setStyleSheet("color: rgb(255, 0, 0);")
        self.pb_reset.setObjectName("pb_reset")
        self.gridLayout_6.addWidget(self.pb_reset, 2, 2, 1, 2)
        self.pb_read = QtWidgets.QPushButton(self.tab_4)
        self.pb_read.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pb_read.setFont(font)
        self.pb_read.setStyleSheet("color: rgb(85, 255, 255);")
        self.pb_read.setObjectName("pb_read")
        self.gridLayout_6.addWidget(self.pb_read, 2, 1, 2, 1)
        self.pb_write = QtWidgets.QPushButton(self.tab_4)
        self.pb_write.setEnabled(False)
        self.pb_write.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pb_write.setFont(font)
        self.pb_write.setStyleSheet("color: rgb(85, 255, 127);")
        self.pb_write.setObjectName("pb_write")
        self.gridLayout_6.addWidget(self.pb_write, 2, 0, 2, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 140))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_otr55 = QtWidgets.QCheckBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_otr55.setFont(font)
        self.cb_otr55.setChecked(True)
        self.cb_otr55.setObjectName("cb_otr55")
        self.verticalLayout.addWidget(self.cb_otr55)
        self.cb_otr218 = QtWidgets.QCheckBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_otr218.setFont(font)
        self.cb_otr218.setObjectName("cb_otr218")
        self.verticalLayout.addWidget(self.cb_otr218)
        self.cb_otr450 = QtWidgets.QCheckBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_otr450.setFont(font)
        self.cb_otr450.setObjectName("cb_otr450")
        self.verticalLayout.addWidget(self.cb_otr450)
        self.horizontalLayout_13.addLayout(self.verticalLayout)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.cb_design_tws = QtWidgets.QCheckBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_design_tws.setFont(font)
        self.cb_design_tws.setObjectName("cb_design_tws")
        self.verticalLayout_10.addWidget(self.cb_design_tws)
        self.horizontalLayout_13.addLayout(self.verticalLayout_10)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.gridLayout_6.addWidget(self.groupBox_10, 1, 0, 1, 2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.cb_sec_order = QtWidgets.QCheckBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_sec_order.setFont(font)
        self.cb_sec_order.setObjectName("cb_sec_order")
        self.gridLayout_14.addWidget(self.cb_sec_order, 0, 0, 1, 1)
        self.cb_coupler_kick = QtWidgets.QCheckBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_coupler_kick.setFont(font)
        self.cb_coupler_kick.setObjectName("cb_coupler_kick")
        self.gridLayout_14.addWidget(self.cb_coupler_kick, 1, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_9, 1, 2, 1, 2)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_12.setEnabled(False)
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 140))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cb_diff = QtWidgets.QCheckBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_diff.setFont(font)
        self.cb_diff.setChecked(True)
        self.cb_diff.setObjectName("cb_diff")
        self.verticalLayout_2.addWidget(self.cb_diff)
        self.horizontalLayout_16.addLayout(self.verticalLayout_2)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.cb_design_tws_2 = QtWidgets.QCheckBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_design_tws_2.setFont(font)
        self.cb_design_tws_2.setObjectName("cb_design_tws_2")
        self.verticalLayout_11.addWidget(self.cb_design_tws_2)
        self.horizontalLayout_16.addLayout(self.verticalLayout_11)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.gridLayout_7.addWidget(self.groupBox_12, 1, 0, 1, 2)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_13.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setSpacing(6)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setSpacing(6)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_16 = QtWidgets.QLabel(self.groupBox_13)
        self.label_16.setEnabled(False)
        self.label_16.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_30.addWidget(self.label_16)
        self.sb_x_group_change = QtWidgets.QDoubleSpinBox(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_x_group_change.setFont(font)
        self.sb_x_group_change.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_x_group_change.setDecimals(1)
        self.sb_x_group_change.setMinimum(-30.0)
        self.sb_x_group_change.setMaximum(30.0)
        self.sb_x_group_change.setSingleStep(0.1)
        self.sb_x_group_change.setProperty("value", 0.0)
        self.sb_x_group_change.setObjectName("sb_x_group_change")
        self.horizontalLayout_30.addWidget(self.sb_x_group_change)
        self.gridLayout_32.addLayout(self.horizontalLayout_30, 0, 1, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setSpacing(6)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_17 = QtWidgets.QLabel(self.groupBox_13)
        self.label_17.setEnabled(False)
        self.label_17.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_28.addWidget(self.label_17)
        self.sb_y_group_change = QtWidgets.QDoubleSpinBox(self.groupBox_13)
        self.sb_y_group_change.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_y_group_change.setFont(font)
        self.sb_y_group_change.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_y_group_change.setDecimals(1)
        self.sb_y_group_change.setMinimum(-30.0)
        self.sb_y_group_change.setMaximum(30.0)
        self.sb_y_group_change.setSingleStep(0.1)
        self.sb_y_group_change.setProperty("value", 0.0)
        self.sb_y_group_change.setObjectName("sb_y_group_change")
        self.horizontalLayout_28.addWidget(self.sb_y_group_change)
        self.gridLayout_32.addLayout(self.horizontalLayout_28, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_13, 1, 3, 2, 1)
        self.widget_6 = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(700, 400))
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_7.addWidget(self.widget_6, 0, 0, 1, 2)
        self.pb_send2server = QtWidgets.QPushButton(self.tab_3)
        self.pb_send2server.setEnabled(False)
        self.pb_send2server.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pb_send2server.setFont(font)
        self.pb_send2server.setStyleSheet("color: rgb(85, 255, 127);")
        self.pb_send2server.setObjectName("pb_send2server")
        self.gridLayout_7.addWidget(self.pb_send2server, 2, 0, 1, 1)
        self.pb_use_go = QtWidgets.QPushButton(self.tab_3)
        self.pb_use_go.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pb_use_go.setFont(font)
        self.pb_use_go.setStyleSheet("color: rgb(85, 255, 255);")
        self.pb_use_go.setCheckable(False)
        self.pb_use_go.setObjectName("pb_use_go")
        self.gridLayout_7.addWidget(self.pb_use_go, 2, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_7 = QtWidgets.QWidget(self.tab_3)
        self.widget_7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(380, 200))
        self.widget_7.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_4.addWidget(self.widget_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_check_bpms = QtWidgets.QPushButton(self.tab_3)
        self.pb_check_bpms.setObjectName("pb_check_bpms")
        self.horizontalLayout_3.addWidget(self.pb_check_bpms)
        self.pb_uncheck_bpms = QtWidgets.QPushButton(self.tab_3)
        self.pb_uncheck_bpms.setObjectName("pb_uncheck_bpms")
        self.horizontalLayout_3.addWidget(self.pb_uncheck_bpms)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout_7.addLayout(self.verticalLayout_4, 0, 3, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.gridLayout_8.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1159, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menuGolden_Orbit = QtWidgets.QMenu(self.menuBar)
        self.menuGolden_Orbit.setObjectName("menuGolden_Orbit")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuLogbook = QtWidgets.QMenu(self.menuBar)
        self.menuLogbook.setObjectName("menuLogbook")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.action_Parameters = QtWidgets.QAction(MainWindow)
        self.action_Parameters.setObjectName("action_Parameters")
        self.actionLoad_Golden_Orbit = QtWidgets.QAction(MainWindow)
        self.actionLoad_Golden_Orbit.setObjectName("actionLoad_Golden_Orbit")
        self.actionSave_Golden_Orbit = QtWidgets.QAction(MainWindow)
        self.actionSave_Golden_Orbit.setObjectName("actionSave_Golden_Orbit")
        self.actionRead_BPMs_Corrs = QtWidgets.QAction(MainWindow)
        self.actionRead_BPMs_Corrs.setObjectName("actionRead_BPMs_Corrs")
        self.actionCalculate_RM = QtWidgets.QAction(MainWindow)
        self.actionCalculate_RM.setObjectName("actionCalculate_RM")
        self.actionCalculate_ORM = QtWidgets.QAction(MainWindow)
        self.actionCalculate_ORM.setObjectName("actionCalculate_ORM")
        self.actionAdaptive_Feedback = QtWidgets.QAction(MainWindow)
        self.actionAdaptive_Feedback.setObjectName("actionAdaptive_Feedback")
        self.actionLoad_GO_from_Orbit_Display = QtWidgets.QAction(MainWindow)
        self.actionLoad_GO_from_Orbit_Display.setObjectName("actionLoad_GO_from_Orbit_Display")
        self.actionSave_corrs = QtWidgets.QAction(MainWindow)
        self.actionSave_corrs.setObjectName("actionSave_corrs")
        self.actionLoad_corrs = QtWidgets.QAction(MainWindow)
        self.actionLoad_corrs.setObjectName("actionLoad_corrs")
        self.actionUncheck_Red = QtWidgets.QAction(MainWindow)
        self.actionUncheck_Red.setObjectName("actionUncheck_Red")
        self.actionGO_Adviser = QtWidgets.QAction(MainWindow)
        self.actionGO_Adviser.setObjectName("actionGO_Adviser")
        self.actionSend_orbit = QtWidgets.QAction(MainWindow)
        self.actionSend_orbit.setObjectName("actionSend_orbit")
        self.actionSend_all = QtWidgets.QAction(MainWindow)
        self.actionSend_all.setObjectName("actionSend_all")
        self.actionTake_Ref_Orbit_from_Server = QtWidgets.QAction(MainWindow)
        self.actionTake_Ref_Orbit_from_Server.setObjectName("actionTake_Ref_Orbit_from_Server")
        self.actionTake_GO_from_Server = QtWidgets.QAction(MainWindow)
        self.actionTake_GO_from_Server.setObjectName("actionTake_GO_from_Server")
        self.menu_File.addAction(self.action_Parameters)
        self.menu_File.addAction(self.actionCalculate_ORM)
        self.menu_File.addAction(self.actionCalculate_RM)
        self.menu_File.addAction(self.actionRead_BPMs_Corrs)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionAdaptive_Feedback)
        self.menuGolden_Orbit.addAction(self.actionLoad_Golden_Orbit)
        self.menuGolden_Orbit.addAction(self.actionSave_Golden_Orbit)
        self.menuGolden_Orbit.addAction(self.actionLoad_GO_from_Orbit_Display)
        self.menuGolden_Orbit.addSeparator()
        self.menuGolden_Orbit.addAction(self.actionTake_Ref_Orbit_from_Server)
        self.menuGolden_Orbit.addAction(self.actionTake_GO_from_Server)
        self.menuGolden_Orbit.addSeparator()
        self.menuGolden_Orbit.addAction(self.actionGO_Adviser)
        self.menuFile.addAction(self.actionSave_corrs)
        self.menuFile.addAction(self.actionLoad_corrs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionUncheck_Red)
        self.menuLogbook.addAction(self.actionSend_orbit)
        self.menuLogbook.addAction(self.actionSend_all)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuGolden_Orbit.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuLogbook.menuAction())
        self.mainToolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cb_otr55, self.cb_otr218)
        MainWindow.setTabOrder(self.cb_otr218, self.cb_otr450)
        MainWindow.setTabOrder(self.cb_otr450, self.cb_design_tws)
        MainWindow.setTabOrder(self.cb_design_tws, self.pb_write)
        MainWindow.setTabOrder(self.pb_write, self.pb_read)
        MainWindow.setTabOrder(self.pb_read, self.pb_reset)
        MainWindow.setTabOrder(self.pb_reset, self.pb_update)
        MainWindow.setTabOrder(self.pb_update, self.cb_sec_order)
        MainWindow.setTabOrder(self.cb_sec_order, self.cb_coupler_kick)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_ref_orb.setText(_translate("MainWindow", "Ref Orb Off"))
        self.pb_calc_orb.setText(_translate("MainWindow", "Calc Orb Off"))
        self.pb_online_orbit.setText(_translate("MainWindow", "Live Orb On"))
        self.pb_golden_orbit.setText(_translate("MainWindow", "Show GO"))
        self.cb_close_orbit.setText(_translate("MainWindow", "Close Orbit"))
        self.pb_reset_all.setText(_translate("MainWindow", "Undo (0)"))
        self.pb_hide_show_dev_panel.setText(_translate("MainWindow", "Show Cor/BPM panel"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Controls"))
        self.pb_feedback.setText(_translate("MainWindow", "Orbit Keeper On"))
        self.label_7.setText(_translate("MainWindow", "alpha (0-orbit. 1-disp)"))
        self.label_12.setText(_translate("MainWindow", "Apply fraction             "))
        self.label_8.setText(_translate("MainWindow", " Repeat in sec"))
        self.pb_apply_kicks.setText(_translate("MainWindow", "Apply Kicks"))
        self.label.setText(_translate("MainWindow", "From"))
        self.label_2.setText(_translate("MainWindow", "To"))
        self.pb_set_pos.setText(_translate("MainWindow", "Set Positions"))
        self.pb_correct_orbit.setText(_translate("MainWindow", "Read and Calculate"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Lattice"))
        self.label_14.setText(_translate("MainWindow", "Subtrain"))
        self.pb_update_lat.setText(_translate("MainWindow", "Update Lattice from DOOCS"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Gentle Correction"))
        self.pb_read_orbit.setText(_translate("MainWindow", "Read Orbit"))
        self.pb_calculate.setText(_translate("MainWindow", "Calculate Correction"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Golden Orbit"))
        self.pb_set_golden.setText(_translate("MainWindow", "Set GO"))
        self.pb_zero_gold.setText(_translate("MainWindow", "Set Zero GO"))
        self.pb_check.setText(_translate("MainWindow", "Check"))
        self.pb_uncheck.setText(_translate("MainWindow", "Uncheck"))
        self.cb_x_cors.setText(_translate("MainWindow", "X"))
        self.cb_y_cors.setText(_translate("MainWindow", "Y"))
        self.cb_caxy.setText(_translate("MainWindow", "CA{X,Y}"))
        self.cb_cbxy.setText(_translate("MainWindow", "CB{X,Y}"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Correctors"))
        self.pb_bpm_check.setText(_translate("MainWindow", "Check"))
        self.pb_bpm_uncheck.setText(_translate("MainWindow", "Uncheck"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "BPMs"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Orbit Correction"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Cavity Controls"))
        self.label_9.setText(_translate("MainWindow", "Voltage Changes [MeV]"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Expert Controls"))
        self.label_13.setText(_translate("MainWindow", "Number of steps"))
        self.label_11.setText(_translate("MainWindow", "Time delay"))
        self.label_10.setText(_translate("MainWindow", "Number of BPM readings"))
        self.pb_start_meas.setText(_translate("MainWindow", "Start Measurement"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Dispersion Measurement"))
        self.pb_update.setText(_translate("MainWindow", "Update Reference"))
        self.pb_reset.setText(_translate("MainWindow", "Reset All"))
        self.pb_read.setText(_translate("MainWindow", "Read from Quads"))
        self.pb_write.setText(_translate("MainWindow", "Write to Quads"))
        self.groupBox_10.setTitle(_translate("MainWindow", "BackTracking"))
        self.cb_otr55.setText(_translate("MainWindow", "OTRC 55"))
        self.cb_otr218.setText(_translate("MainWindow", "OTRB 218"))
        self.cb_otr450.setText(_translate("MainWindow", "OTRB 450"))
        self.cb_design_tws.setText(_translate("MainWindow", "Design Twiss"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Calc Options"))
        self.cb_sec_order.setText(_translate("MainWindow", "Second Order"))
        self.cb_coupler_kick.setText(_translate("MainWindow", "Coupler Kick"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Twiss Monitor"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Options"))
        self.cb_diff.setText(_translate("MainWindow", "Difference"))
        self.cb_design_tws_2.setText(_translate("MainWindow", "Design Twiss"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Group Controls"))
        self.label_16.setText(_translate("MainWindow", "X: Group Changing"))
        self.label_17.setText(_translate("MainWindow", "X: Group Changing"))
        self.pb_send2server.setText(_translate("MainWindow", "Send To Server"))
        self.pb_use_go.setText(_translate("MainWindow", "Use Golden Orbit"))
        self.pb_check_bpms.setText(_translate("MainWindow", "Check"))
        self.pb_uncheck_bpms.setText(_translate("MainWindow", "Uncheck"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "GO Editor"))
        self.menu_File.setTitle(_translate("MainWindow", "&Expert Panel"))
        self.menuGolden_Orbit.setTitle(_translate("MainWindow", "Golden Orbit"))
        self.menuFile.setTitle(_translate("MainWindow", "Correctors"))
        self.menuLogbook.setTitle(_translate("MainWindow", "Logbook"))
        self.action_Parameters.setText(_translate("MainWindow", "Settings"))
        self.actionLoad_Golden_Orbit.setText(_translate("MainWindow", "Load Golden Orbit"))
        self.actionSave_Golden_Orbit.setText(_translate("MainWindow", "Save Golden Orbit"))
        self.actionRead_BPMs_Corrs.setText(_translate("MainWindow", "Read BPMs and Corrs"))
        self.actionCalculate_RM.setText(_translate("MainWindow", "Calculate ORM and DRM"))
        self.actionCalculate_ORM.setText(_translate("MainWindow", "Calculate ORM"))
        self.actionAdaptive_Feedback.setText(_translate("MainWindow", "Adaptive Feedback"))
        self.actionLoad_GO_from_Orbit_Display.setText(_translate("MainWindow", "Load GO from Orbit Display"))
        self.actionSave_corrs.setText(_translate("MainWindow", "Save"))
        self.actionLoad_corrs.setText(_translate("MainWindow", "Load"))
        self.actionUncheck_Red.setText(_translate("MainWindow", "Uncheck Red"))
        self.actionGO_Adviser.setText(_translate("MainWindow", "GO Adviser"))
        self.actionSend_orbit.setText(_translate("MainWindow", "Send only orbit"))
        self.actionSend_all.setText(_translate("MainWindow", "Send all"))
        self.actionTake_Ref_Orbit_from_Server.setText(_translate("MainWindow", "DOOCS Ref Orbit -> GO"))
        self.actionTake_GO_from_Server.setText(_translate("MainWindow", "DOOCS GO -> GO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

